import time
# A text adventure game program
# Title - Escape the Serial Killer
# Scenario changes based on user choice

# Welcome screen to be dipalyed

print()
print()
print("      *******************************************")
print("      *                                         *")
print("      *            You have to escape           *")
time.sleep(3)
print("      *                                         *")
print("      *          or be the next victim...       *")
print("      *                                         *")
print("      *******************************************")
print()
time.sleep(2)

# get user name
user_name = input("Enter your name: ").capitalize()
print()
time.sleep(2)

# start game
game_start = input("Would you like to start the game? (Y/N): ")
print("NOTE: Options you can choose from are in CAPITAL LETTERS.\n")


# win or lose message
win = ("\nCongratulations! You escaped the serial killers house. \
It is a strange area however. Leaving his house was the least of your problems.")
lose = ("\nYou failed to escape the serial killers house. Will \
your head be the next on to go in his cabinet?")

# start game

# not play game
if game_start == "n" or game_start == "N":
    time.sleep(2)
    print("Alright. Maybe next time")

# play game
elif game_start == "y" or game_start == "Y":
    time.sleep(2)
    print("You jolt awake with a start as a terrifying thundercloud echoes.")
    time.sleep(3)
    print("BOOM!!")
    time.sleep(2)
    print("Your heart is racing as the thundercloud wrenched you from the peaceful \
slumber you were in.")
    time.sleep(4)
    print("Was it really peaceful? You don’t know.")
    time.sleep(2)
    print("You are confused and disoriented and can’t remember anything.")
    time.sleep(3)
    print("Who am I? Where am I? What’s going on? ")
    time.sleep(3)
    print("These are questions that run through your mind but no matter how hard you \
try you can’t seem to get any answers.")
    time.sleep(4)
    print("You look up.")
    time.sleep(2)
    print("A single fluorescent bulb lights up the room you are in.")
    time.sleep(3)
    print("It blinks once.")
    time.sleep(2)
    print("It blinks again.")
    time.sleep(2)
    print("You study your body.")
    time.sleep(2)
    print("Your wrists are rubbed red as if your hands were once tied up -- and \
you can see a faint rope imprint on your wrists.")
    time.sleep(4)
    print("Your legs look fine.")
    time.sleep(2)
    print("You feel okay.")
    time.sleep(2)
    print("What happened to you?")
    time.sleep(2)
    print("You can’t tell.")
    time.sleep(2)
    print()

    look_room = input("Would you like to LOOK around the room? ")
    time.sleep(2)
    print()
    look_room = look_room.lower()

    # look at room conditionals
    if look_room == "look":

        # looking around room
        print("You look around the room.")
        time.sleep(2)
        print("There are no windows.")
        time.sleep(2)
        print("The room is bare save for a small stool close to the door.")
        time.sleep(3)
        print("There is a folded white paper on the stool.")
        time.sleep(2)
        print("You are lying on a rickety hospital bed with nothing else on it.")
        time.sleep(3)
        print("The walls of the room seem like they were once white but now they are \
badly stained.")
        time.sleep(4)
        print("You look at the walls more closely.")
        time.sleep(2)
        print("There is a mark on the wall close to the door which looks like a \
handprint.")
        time.sleep(4)
        print("A bloody handprint.")
        time.sleep(2)
        print("You look away.")
        time.sleep(2)
        print("What is going on?")
        time.sleep(2)
        print()

        option_one = input("Would you like to go to the DOOR or pick up the PAPER \
on the stool? ")
        time.sleep(2)
        print()

        # option one conditions
        if option_one.lower() == "paper":

            # picking up the paper
            print("You stand up and walk towards the stool.")
            time.sleep(2)
            print("The stool looks very old and is missing a leg.")
            time.sleep(2)
            print("It’s balanced on the adjacent wall.")
            time.sleep(2)
            print("You bend down and pick up the folded paper.")
            time.sleep(2)
            print("The paper looks new and you wonder if it was left for you to find.")
            time.sleep(3)
            print()

            option_two = input("Would you like to UNFOLD the paper? ")
            time.sleep(2)
            print()
            option_two = option_two.lower()

            # option two conditionals
            if option_two == "unfold":

                # unfolding paper
                print("You open the paper.")
                time.sleep(2)
                print("There’s not a lot on the paper.")
                time.sleep(2)
                print("Looks like there is a name written down.")
                time.sleep(2)
                print(f"{user_name}.")
                time.sleep(2)
                print("Is this your name? You can’t help but wonder.")
                time.sleep(2)
                print("There’s also an address written down.")
                time.sleep(2)
                print("No 5, Kale Street.")
                time.sleep(2)
                print("Is it the address of where you are right now?")
                time.sleep(3)
                print("Is it your home address?")
                time.sleep(2)
                print("Where is this place?")
                time.sleep(2)
                print("You are even more confused and decide you need more answers.")
                time.sleep(3)
                print("Maybe a search of the house you are in will provide more answers.")
                time.sleep(3)
                print()

                # option three
                option_three = input("Would you like to LEAVE the room? ")
                time.sleep(2)
                print()
                option_three = option_three.lower()

            else:
                print("You should have unfolded the paper")

        # option one of option three        
        if option_one == "door" or option_three == "leave":

            # go to the room door 
            print("You go to the door and attempt to open it.")
            time.sleep(2)
            print("It’s unlocked.")
            time.sleep(2)
            print("You step out of the room and find your self in a hallway.")
            time.sleep(3)
            print("The only other place is a room at the end of the hallway.")
            time.sleep(3)
            print("You begin to walk down the hallway.")
            time.sleep(2)
            print("You can smell something strange.")
            time.sleep(2)
            print("The hallway floor is bare.")
            time.sleep(2)
            print("Just a concrete floor.")
            time.sleep(2)
            print("You notice some paintings on the walls as you walk down.")
            time.sleep(3)
            print("A painting of a woman with a dismembered arm.")
            time.sleep(3)
            print("Her head is missing.")
            time.sleep(2)
            print("A painting of a woman lying on the ground in a pool of blood.")
            time.sleep(3)
            print("Her upper body is separated from her lower body.")
            time.sleep(3)
            print("Her head is also missing.")
            time.sleep(2)
            print("You see a painting that’s bigger than the rest.")
            time.sleep(3)
            print("A painting of a grinning man standing in front of a large cabinet.")
            time.sleep(3)
            print("There are large jars on the shelf with masses in them.")
            time.sleep(3)
            print("You study the painting closely.")
            time.sleep(2)
            print("The masses look like dismembered female heads.")
            time.sleep(2)
            print("Fear.")
            time.sleep(2)
            print("You start getting terrified.")
            time.sleep(2)
            print("Who would hang up such paintings?")
            time.sleep(2)
            print("You?")
            time.sleep(2)
            print("Someone else?")
            time.sleep(2)
            print("You see a staircase going up beside the room.")
            time.sleep(2)
            print("A way out?")
            time.sleep(2)
            print()

            option_four = input("Would you like to go UP the stairs or enter the ROOM? ")
            time.sleep(2)
            print()
            option_four = option_four.lower()

            # option four conditionals
            if option_four == "up":

                # go up stairs
                print("You climb the stairs.")
                time.sleep(2)
                print("Where could it lead?")
                time.sleep(2)
                print("The fear of the unknown is making your body shake.")
                time.sleep(2)
                print("You find yourself in a room.")
                time.sleep(2)
                print("The room is unkempt.")
                time.sleep(2)
                print("Extremely unkempt.")
                time.sleep(2)
                print("Empty cans are everywhere.")
                time.sleep(2)
                print("Alcohol bottles as well.")
                time.sleep(2)
                print("Takeout boxes litter the floor.")
                time.sleep(2)
                print("A number of other items are all over the room.")
                time.sleep(3)
                print("It smells really rank in here.")
                time.sleep(2)
                print("You gag.")
                time.sleep(2)
                print("It looks like the room hasn’t been cleaned for a long time.")
                time.sleep(3)
                print("More paintings are hung up on the walls of the room and an easel \
is shoved into a corner.")
                time.sleep(4)
                print("There is a bed in one corner of the room.")
                time.sleep(2)
                print("Someone sleeps here.")
                time.sleep(2)
                print("There is a small wardrobe beside a window.")
                time.sleep(3)
                print("A window!")
                time.sleep(2)
                print("The first one you have seen in here.")
                time.sleep(2)
                print("There is a door beside the window.")
                time.sleep(2)
                print("A way to leave the terrifying house?")
                time.sleep(3)
                print("You have to take the chance.")
                time.sleep(2)
                print("You walk towards the door.")
                time.sleep(2)
                print("It is locked.")
                time.sleep(2)
                print("The window is shut tightly and has bars over it.")
                time.sleep(3)
                print("No way to leave.")
                time.sleep(2)
                print("Maybe you can get more answers in the room downstairs?")
                time.sleep(3)
                print("Who knows maybe a key too?")
                time.sleep(2)
                print()

                option_five = input("Would you like to go DOWN? ")
                time.sleep(2)
                print()
                option_five = option_five.lower()

                # option five conditions

                # go back down stairs
                if option_five == "down":
                    print("You are downstairs.")
                    time.sleep(2)
                    print()

                    # option six
                    option_six = input("Would you like to ENTER the other room? ")
                    time.sleep(2)
                    print()
                    option_six = option_six.lower()

            # option four or six
            if option_four == "room" or option_six == "enter":

                # enter the room at the end of the hallway
                print("You are the entrance of the other room.")
                time.sleep(2)
                print("You walk in.")
                time.sleep(2)
                print("There is a chair to the left of you.")
                time.sleep(2)
                print("There is also a man bent over a table.")
                time.sleep(2)
                print("The first person you are meeting here.")
                time.sleep(2)
                print("You can’t see what he is doing.")
                time.sleep(2)
                print("You look around.")
                time.sleep(2)
                print("It is absolutely horrifying.")
                time.sleep(2)
                print("You can’t notice any other thing except the bodies.")
                time.sleep(3)
                print("There are three of them propped against a wall.")
                time.sleep(3)
                print("All with missing heads.")
                time.sleep(2)
                print("You can’t help the horrified gasps that leaves your mouth.")
                time.sleep(3)
                print("The man drops something on the floor.")
                time.sleep(2)
                print("It’s a knife.")
                time.sleep(2)
                print("He stands up and faces you.")
                time.sleep(2)
                print("There is mask on his face.")
                time.sleep(2)
                print("Panic is starting to set in and you turn to leave the room.")
                time.sleep(3)
                print("He yells.")
                time.sleep(2)
                print("‘SIT DOWN!’")
                time.sleep(2)
                print("You freeze.")
                time.sleep(2)
                print("His voice is the most terrifying thing you have ever heard.")
                time.sleep(4)
                print()

                option_seven = input("Would you like to SIT down or RUN out \
from the room? ")
                time.sleep(2)
                print()
                option_seven = option_seven.lower()

                # option seven conditions
                if option_seven == "run":

                    # run away from man
                    print("You ignore his words and sprint out from the room.")
                    time.sleep(3)
                    print("You climb up the stairs hastily and enter a room.")
                    time.sleep(3)
                    print("You barely register anything except the door.")
                    time.sleep(2)
                    print("You can hear him thundering up the stairs.")
                    time.sleep(2)
                    print("More panic.")
                    time.sleep(2)
                    print("You can't let him catch you.")
                    time.sleep(2)
                    print("You run towards the door.")
                    time.sleep(2)
                    print("Please let it be open.")
                    time.sleep(2)
                    print("You turn the handle.")
                    time.sleep(2)
                    print("It’s locked and there's no key.")
                    time.sleep(2)
                    print("Oh no.")
                    time.sleep(2)
                    print("There is no escaping for you.")
                    time.sleep(2)
                    print("You hear the man’s footsteps behind you.")
                    time.sleep(3)
                    print("‘Where do you think you are going?’")
                    time.sleep(2)
                    print("‘You can’t leave me’")
                    time.sleep(2)
                    print("‘Not again’")
                    time.sleep(2)
                    print("He comes up behind you grabs your shoulders.")
                    time.sleep(3)
                    print("You are frozen in place.")
                    time.sleep(2)
                    print("He says eerily:")
                    time.sleep(2)
                    print("‘You will never leave me again’")
                    time.sleep(2)
                    print("Something smashes into the back of your head.")
                    time.sleep(3)
                    print("There is only blackness now.")
                    time.sleep(4)

                    # you have failed to escape the serial killer
                    print(lose)

                elif option_seven == "sit":

                    # sit on the chair and think
                    print("You sit down on the chair close to the entrance.")
                    time.sleep(2)
                    print("The man studies you silently.")
                    time.sleep(2)
                    print("You feel like you are going to pass out from fear.")
                    time.sleep(4)
                    print("However you decide to calm down and plan your next move.")
                    time.sleep(4)
                    print("You look around the room.")
                    time.sleep(2)
                    print("It looks like a laboratory of some sort.")
                    time.sleep(2)
                    print("On the floor right beside your chair is a bottle of bleach.")
                    time.sleep(4)
                    print("There is a cabinet to your right and you can see some jars \
with masses inside them.")
                    time.sleep(4)
                    print("You remember the painting.")
                    time.sleep(2)
                    print("You gulp down your panic.")
                    time.sleep(2)
                    print("There is also a gurney in the room.")
                    time.sleep(2)
                    print("The bodies propped up against the wall are on your left.")
                    time.sleep(3)
                    print("One of the bodies has a knife sticking out from the chest.")
                    time.sleep(3)
                    print("They are covered in blood and it makes you sick.")
                    time.sleep(3)
                    print("You have to close your eyes to try and stay calm.")
                    time.sleep(3)
                    print("The man laughs.")
                    time.sleep(2)
                    print("You look up.")
                    time.sleep(2)
                    print("He says:")
                    time.sleep(2)
                    print("‘Don’t be worried’")
                    time.sleep(2)
                    print("‘These ones just didn’t listen’")
                    time.sleep(2)
                    print("Another maniacal laugh.")
                    time.sleep(2)
                    print("You study him.")
                    time.sleep(2)
                    print("The man is tall and wearing a stained lab coat.")
                    time.sleep(3)
                    print("He is wearing a mask covering the lower half of his face.")
                    time.sleep(3)
                    print("You look at his eyes.")
                    time.sleep(2)
                    print("They are two pools of terrifying blackness.")
                    time.sleep(2)
                    print("This time you can’t hide the shiver that moves though you.")
                    time.sleep(3)
                    print("His head is bald and has some stitches.")
                    time.sleep(2)
                    print("He stands in front of a table but you can’t see what is on \
the table.")
                    time.sleep(4)
                    print("There is something that looks like a huge freezer \
behind the table.")
                    time.sleep(4)
                    print("There is a key on top of the freezer.")
                    time.sleep(2)
                    print("A key?")
                    time.sleep(2)
                    print("Could it be the key to your freedom?")
                    time.sleep(3)
                    print("‘All you are doing is pointless’")
                    time.sleep(2)
                    print("‘You can never escape’")
                    time.sleep(2)
                    print("He turns and sits back at the table.")
                    time.sleep(2)
                    print("Impossible.")
                    time.sleep(2)
                    print("You are going to escape.")
                    time.sleep(2)
                    print("You ponder on how you’ll do that.")
                    time.sleep(2)
                    print("Ideas come up.")
                    time.sleep(2)
                    print("You smile.")
                    time.sleep(2)
                    print()

                    option_eight = input("Would you like to grab the bottle of BLEACH \
or take the KNIFE from the corpse? ")
                    time.sleep(2)
                    print()
                    option_eight = option_eight.lower()

                    # option eight conditions
                    if option_eight == "bleach":

                        # escape by splashing bleach into mans eyes
                        print("You lean down and take the bottle of bleach close to \
your feet.")
                        time.sleep(3)
                        print("A plan begins to form in your head.")
                        time.sleep(2)
                        print("Maybe you can escape this house.")
                        time.sleep(2)
                        print("You open the bottle.")
                        time.sleep(2)
                        print("Good.")
                        time.sleep(2)
                        print("This is enough.")
                        time.sleep(2)
                        print("You stand up slowly and walk towards the man.")
                        time.sleep(3)
                        print("You scream.")
                        time.sleep(2)
                        print("The man abruptly turns back and you throw the bleach \
towards his eyes.")
                        time.sleep(4)
                        print("He howls.")
                        time.sleep(2)
                        print("For a moment, you are frozen when you hear his ghastly \
howl.")
                        time.sleep(4)
                        print("That is the howl of darkness.")
                        time.sleep(2)
                        print("You come to your senses and grab the key on the freezer.")
                        time.sleep(3)
                        print("RUN! RUN!! RUN!!!")
                        time.sleep(2)
                        print("That’s all you can think of right now.")
                        time.sleep(2)
                        print("He screams:")
                        time.sleep(2)
                        print("‘GET BACK HERE!’")
                        time.sleep(2)
                        print("You ignore his words and sprint out from the room.")
                        time.sleep(3)
                        print("You climb up the stairs hastily and enter a room.")
                        time.sleep(3)
                        print("You barely register anything except the door at the \
far end.")
                        time.sleep(3)
                        print("He is cursing and stumbling around coming up the stairs.")
                        time.sleep(3)
                        print("More panic.")
                        time.sleep(2)
                        print("You can’t let him catch you.")
                        time.sleep(2)
                        print("You run towards the door.")
                        time.sleep(2)
                        print("You turn the handle.")
                        time.sleep(2)
                        print("It’s locked.")
                        time.sleep(2)
                        print("You see a keyhole in the door, jam the key into it \
and turn.")
                        time.sleep(3)
                        print("One click.")
                        time.sleep(2)
                        print("Two clicks.")
                        time.sleep(2)
                        print("You turn the handle again.")
                        time.sleep(2)
                        print("You can hear the man stumbling about the room.")
                        time.sleep(3)
                        print("‘Where do you think you are going?’")
                        time.sleep(2)
                        print("‘You can’t leave me’")
                        time.sleep(2)
                        print("‘Not again’")
                        time.sleep(2)
                        print("The door swings open.")
                        time.sleep(2)
                        print("The frenzy wind whips about and it’s still raining \
but you don’t care.")
                        time.sleep(4)
                        print("Escaping is all you can care about.")
                        time.sleep(2)
                        print("You step out.")
                        time.sleep(2)
                        print("You hear the man’s chilling words as you leave.")
                        time.sleep(3)
                        print("‘I’ll get you back, don’t worry’")
                        time.sleep(3)
                        print("The door slams behind you.")
                        time.sleep(4)

                        # you have escaped the serial killer
                        print(win)

                    elif option_eight == "knife":

                        # escape using a knife to stab man
                        print("A plan begins to form in your head.")
                        time.sleep(2)
                        print("Maybe you can escape this house.")
                        time.sleep(2)
                        print("You stand up slowly and walk towards the corpses.")
                        time.sleep(3)
                        print("The entire arrangement is even more horrifying up close.")
                        time.sleep(3)
                        print("You say a quick prayer for forgiveness and you approach \
the corpse with the knife in its chest.")
                        time.sleep(4.5)
                        print("Tears are running down your face as you grab the knife hilt.")
                        time.sleep(4)
                        print("You start to pull it out and it makes a horrible \
squelching sound.")
                        time.sleep(4)
                        print("Oh no.")
                        time.sleep(2)
                        print("You quickly turn back to look at the man.")
                        time.sleep(2)
                        print("No reaction.")
                        time.sleep(2)
                        print("Whew.")
                        time.sleep(2)
                        print("A breath of relief.")
                        time.sleep(2)
                        print("Looks like the sound of the rain masks the squelching \
sound.")
                        time.sleep(3)
                        print("You finally pull the knife out and get up to walk towards \
the man.")
                        time.sleep(4)
                        print("You scream.")
                        time.sleep(2)
                        print("The man abruptly turns back and you push the knife into \
his stomach.")
                        time.sleep(3)
                        print("You expect to feel shocked by the act but you don’t.")
                        time.sleep(3)
                        print("Huh? What does that mean?")
                        time.sleep(2)
                        print("Why does the act feel familiar?")
                        time.sleep(2)
                        print("He howls.")
                        time.sleep(2)
                        print("You can’t ponder on your thoughts when you hear his howl.")
                        time.sleep(3)
                        print("That is the howl of darkness.")
                        time.sleep(2)
                        print("You come to your senses and grab the key on the freezer.")
                        time.sleep(3)
                        print("RUN! RUN!! RUN!!!")
                        time.sleep(2)
                        print("That’s all you can think of right now.")
                        time.sleep(2)
                        print("He screams:")
                        time.sleep(2)
                        print("‘GET BACK HERE!’")
                        time.sleep(2)
                        print("You ignore his words and sprint out from the room.")
                        time.sleep(3)
                        print("You climb up the stairs hastily and enter a room.")
                        time.sleep(3)
                        print("You barely register anything except the door at the \
far end.")
                        time.sleep(3)
                        print("He is cursing and stumbling around coming up the stairs.")
                        time.sleep(3)
                        print("More panic.")
                        time.sleep(2)
                        print("You can’t let him catch you.")
                        time.sleep(2)
                        print("You run towards the door.")
                        time.sleep(2)
                        print("You turn the handle.")
                        time.sleep(2)
                        print("It’s locked.")
                        time.sleep(2)
                        print("You see a keyhole in the door, jam the key into it \
and turn.")
                        time.sleep(3)
                        print("One click.")
                        time.sleep(2)
                        print("Two clicks.")
                        time.sleep(2)
                        print("You turn the handle again.")
                        time.sleep(2)
                        print("You can hear the man stumbling about the room.")
                        time.sleep(3)
                        print("‘Where do you think you are going?’")
                        time.sleep(3)
                        print("‘You can’t leave me’")
                        time.sleep(2)
                        print("‘Not again’")
                        time.sleep(2)
                        print("The door swings open.")
                        time.sleep(2)
                        print("The frenzy wind whips about and it’s still raining \
but you don’t care.")
                        time.sleep(4)
                        print("Escaping is all you can care about.")
                        time.sleep(2)
                        print("You step out.")
                        time.sleep(2)
                        print("You hear the man’s chilling words as you leave.")
                        time.sleep(3)
                        print("‘I’ll get you back, don’t worry’")
                        time.sleep(2)
                        print("The door slams behind you.")
                        time.sleep(4)

                        # you have escaped the serial killer
                        print(win)

 # else blocks to handle several conditions 
 #                        
                    else:
                        print("You should have chosen a required option")

                else:
                    print("You should have chosen a required option")

            else:
                print("You should have chosen a required option")

        else:
            print("You should have chosen a required option")

    else:
        print("You should have looked around the room.")

else:
    print("Invalid input entered")